### ISSUE TITLE
gem in Version 1.2.1 seems to be broken

### ISSUE THREAD

**Issue by PhilippGoecke** [cdinger/scenic-oracle_adapter#14]
when you download https://rubygems.org/downloads/scenic-oracle_adapter-1.2.1.gem the data.tar.gz within the gemfile is far too small.

who can fix this?

thanks in advance!

**Comment by PhilippGoecke** [comment]
And when using the new Release i get an Error:

> ...
> NameError: uninitialized constant Scenic::Adapters::Oracle
> config/initializers/scenic.rb:4:in `block in <top (required)>'
> vendor/ruby/3.0.0/gems/scenic-1.7.0/lib/scenic/configuration.rb:35:in `configure'
> ...

**Comment by cdinger** [comment]
Thanks for reporting, @PhilippGoecke. I'm not sure what happened here, but he published gem file didn't contain any actual source code.

1.2.1 has been yanked and I'll push out a 1.2.2 release soon.

**Comment by cdinger** [comment]
@PhilippGoecke 1.2.2 has been pushed to rubygems.org. I've pulled it into one of my projects and it appears to be behaving. Let me know if you have any issues. Thanks again!

**Comment by PhilippGoecke** [comment]
@cdinger Version 1.2.2 works as expected - thanks for the fast fix!
