### ISSUE TITLE
Should `update_view` work for materialized views

### ISSUE THREAD

**Issue by IanWhitney** [cdinger/scenic-oracle_adapter#15]
Should this work as a migration?

```ruby
    update_view :my_mview,
      version: 2,
      revert_to_version: 1,
      materialized: true
```

When we tried it we got errors from Oracle about a syntax problem. But switching to a `drop_view` followed by `create_view` worked fine.

**Comment by cdinger** [comment]
@IanWhitney this should work as long as version 1 is also materialized. If you can re-generate the error message, I'd be curious to see it.

**Comment by IanWhitney** [comment]
Yep. User error somewhere. This works fine.

**Comment by IanWhitney** [comment]
I think I figured this out. If you try to update a mview but your new query is exactly the same as the mview's current query you will get this error. Why? I have no idea.
