### ISSUE TITLE
Bug in 1.3.1 if a dependency is `user_scheduler_jobs`

### ISSUE THREAD

**Issue by whit0694** [cdinger/scenic-oracle_adapter#18]
If I have an mview that has a dependency on `user_scheduler_jobs` then schema dumping fails with a KeyError. This only occurs in 1.3.1, so I'm guessing (but haven't yet proved) that it occurs [here](https://github.com/cdinger/scenic-oracle_adapter/compare/v1.3.0...v1.3.1#diff-702381f54d28ba75a5ae074024795ae0362356a59e454ec5ed7d4df1140857d6R86) as that's the only part of the new code that does anything with hashes.

I'm going to dig in to this more.

**Comment by whit0694** [comment]
The problem is actually in tsort, since it expects every dependency to have a matching key somewhere in the hash.

But the hash keys are only user-created mviews/views, since that's what `view_dependencies` is selecting.

So if a user-created mview/view has a dependency on a db object that's _not_ user-created, then tsort fails

This version of `dependency_order` works by removing any dependency that's not user-created.

```ruby
def dependency_order
  views_hash = TSortableHash.new
  user_managed_object_names = view_dependencies.map { |x| x["name"] }

  view_dependencies.each do |view_data|
    views_hash[view_data["name"]] ||= []
    next if !user_managed_object_names.include?(view_data["dependency"])
    views_hash[view_data["name"]] << view_data["dependency"]
  end
end

```

I figure we only want user-created things in `schema.rb` so excluding them here makes sense.

**Comment by whit0694** [comment]
Another fix would be in the `view_dependencies` query, adding a check so that it only returns user-managed dependencies

```
        select_all(<<~EOSQL)
          select lower(uo.object_name) as name, lower(ud.referenced_name) as dependency
          from user_objects uo
            left join user_dependencies ud on uo.object_name = ud.name
              and ud.referenced_type in ('VIEW', 'MATERIALIZED VIEW')
              and ud.referenced_name in (select object_name from user_objects)
          where uo.object_type in ('VIEW', 'MATERIALIZED VIEW')
        EOSQL
```

**Comment by whit0694** [comment]
@cdinger I can do a PR, but do you have a preference on the approach?

**Comment by cdinger** [comment]
@whit0694 I prefer the query fix. I'm still trying to reproduce this. What method are you using to add the scheduler? Are you creating a materialized view with the refresh clause? Or something else?

**Comment by whit0694** [comment]
I have an mview that uses [this query](https://gist.github.com/whit0694/8ea3296e00f20ae3ce1688ffc55346b2) which makes a bunch of `user_scheduler...` tables dependencies of the mview.

**Comment by cdinger** [comment]
Oh, I see. This totally makes sense now. Yeah, there are all kinds of other objects that could appear in these dependencies.

I really like your query fix–nice and tidy. Thank you!
