### ISSUE TITLE
Requiring OCI8

### ISSUE THREAD

**Issue by bmulvihill** [cdinger/scenic-oracle_adapter#8]
@cdinger I was looking to include this gem in one of my projects, but it requires the OCI8 gem.  We use JRuby w/ our application so we cannot use OCI8.

Is it possible to have that dependency removed?

**Comment by cdinger** [comment]
@bmulvihill good suggestion! I'll push out a new release after the CI runs.

**Comment by cdinger** [comment]
@bmulvihill 1.0.2 has been pushed out to rubygems.org. ruby-oci8 has been changed to a development dependency.

**Comment by bmulvihill** [comment]
@cdinger Thanks!
